---
- name: Add Kubernetes APT Repo Key
  shell: |
    set -o pipefail
    curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
  args:
    executable: /bin/bash

- name: Add Kubernetes APT Repo
  shell: |
    set -o pipefail
    echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list
  args:
    executable: /bin/bash

- name: Update APT Cache
  apt: update_cache=yes

- name: Install Kube ADM
  package:
    name: kubeadm
    state: present

- name: Install Kube Cuddle
  package:
    name: kubectl
    state: present

- name: Install Kubelet
  package:
    name: kubelet
    state: present

- name: Ensure Kubelet is started and enabled at boot.
  service:
    name: kubelet
    state: started
    enabled: true

- name: Copy /etc/default/kubelet
  template: src=kubelet.j2 dest=/etc/default/kubelet

#- name: Move kubelet to mgmt VRF (Cumulus)
#  lineinfile: dest=/etc/systemd/system/kubelet.service.d/10-kubeadm.conf
#              regexp="^ExecStart=\/usr\/bin\/kubelet"
#              line="/usr/bin/vrf task exec mgmt /usr/bin/kubelet"
#              state=present
#  when: is_cumulus.rc == 0

#- name: Join kubernetes cluster. 
#  shell: |
#    set -o pipefail
#    kubeadm join {{ kubernetes_cluster_api_ip }}:6443 --token {{ kubernetes_token }} --discovery-token-ca-cert-hash {{ kubernetes_ca_cert_hash }} --node-name {{ target }} --ignore-preflight-errors=all
#  args:
#    executable: /bin/bash
