---
- hosts: '{{ target }}'
  remote_user: '{{ remote_user }}'
  become: yes
  become_method: sudo

  roles:
    - init
    - apt-cache
    - enable-routing
    - docker
    - kubelet
    - provisioned
